"""add financial management tables

Revision ID: 710c0d21c090
Revises: 001
Create Date: 2025-05-18 04:09:12.570014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710c0d21c090'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('nome', sa.String(), nullable=False))
    op.add_column('goals', sa.Column('valor_alvo', sa.Float(), nullable=False))
    op.add_column('goals', sa.Column('valor_atual', sa.Float(), nullable=False))
    op.add_column('goals', sa.Column('prazo', sa.Date(), nullable=True))
    op.add_column('goals', sa.Column('tipo', sa.String(), nullable=False))
    op.add_column('goals', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.drop_constraint('goals_user_id_fkey', 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'users', ['usuario_id'], ['id'])
    op.drop_column('goals', 'target_amount')
    op.drop_column('goals', 'current_amount')
    op.drop_column('goals', 'name')
    op.drop_column('goals', 'user_id')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('goals', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('current_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('target_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key('goals_user_id_fkey', 'goals', 'users', ['user_id'], ['id'])
    op.drop_column('goals', 'usuario_id')
    op.drop_column('goals', 'tipo')
    op.drop_column('goals', 'prazo')
    op.drop_column('goals', 'valor_atual')
    op.drop_column('goals', 'valor_alvo')
    op.drop_column('goals', 'nome')
    # ### end Alembic commands ### 